# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4303c1df60fea42b741ecd36bfc274d3e1aa019915ec157d3f7f0e0a48e6b614643a5bf21d693b58a69c32ca84b7e10f9583bc3529c6e23ad0d39838735a767c

test:
  secret_key_base: c77cdf4696776f9ed9ea98b4e3bce7a94bdbac39ce267871314e62ecb2b74fc81ad605017fd9c2f20ac9f4c7d6186ed393489d3015bc8f06961e8c30c2a728be

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
