require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe MiniLecturesController, :type => :controller do

  # This should return the minimal set of attributes required to create a valid
  # MiniLecture. As you add validations to MiniLecture, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # MiniLecturesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all mini_lectures as @mini_lectures" do
      mini_lecture = MiniLecture.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:mini_lectures)).to eq([mini_lecture])
    end
  end

  describe "GET show" do
    it "assigns the requested mini_lecture as @mini_lecture" do
      mini_lecture = MiniLecture.create! valid_attributes
      get :show, {:id => mini_lecture.to_param}, valid_session
      expect(assigns(:mini_lecture)).to eq(mini_lecture)
    end
  end

  describe "GET new" do
    it "assigns a new mini_lecture as @mini_lecture" do
      get :new, {}, valid_session
      expect(assigns(:mini_lecture)).to be_a_new(MiniLecture)
    end
  end

  describe "GET edit" do
    it "assigns the requested mini_lecture as @mini_lecture" do
      mini_lecture = MiniLecture.create! valid_attributes
      get :edit, {:id => mini_lecture.to_param}, valid_session
      expect(assigns(:mini_lecture)).to eq(mini_lecture)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new MiniLecture" do
        expect {
          post :create, {:mini_lecture => valid_attributes}, valid_session
        }.to change(MiniLecture, :count).by(1)
      end

      it "assigns a newly created mini_lecture as @mini_lecture" do
        post :create, {:mini_lecture => valid_attributes}, valid_session
        expect(assigns(:mini_lecture)).to be_a(MiniLecture)
        expect(assigns(:mini_lecture)).to be_persisted
      end

      it "redirects to the created mini_lecture" do
        post :create, {:mini_lecture => valid_attributes}, valid_session
        expect(response).to redirect_to(MiniLecture.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved mini_lecture as @mini_lecture" do
        post :create, {:mini_lecture => invalid_attributes}, valid_session
        expect(assigns(:mini_lecture)).to be_a_new(MiniLecture)
      end

      it "re-renders the 'new' template" do
        post :create, {:mini_lecture => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested mini_lecture" do
        mini_lecture = MiniLecture.create! valid_attributes
        put :update, {:id => mini_lecture.to_param, :mini_lecture => new_attributes}, valid_session
        mini_lecture.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested mini_lecture as @mini_lecture" do
        mini_lecture = MiniLecture.create! valid_attributes
        put :update, {:id => mini_lecture.to_param, :mini_lecture => valid_attributes}, valid_session
        expect(assigns(:mini_lecture)).to eq(mini_lecture)
      end

      it "redirects to the mini_lecture" do
        mini_lecture = MiniLecture.create! valid_attributes
        put :update, {:id => mini_lecture.to_param, :mini_lecture => valid_attributes}, valid_session
        expect(response).to redirect_to(mini_lecture)
      end
    end

    describe "with invalid params" do
      it "assigns the mini_lecture as @mini_lecture" do
        mini_lecture = MiniLecture.create! valid_attributes
        put :update, {:id => mini_lecture.to_param, :mini_lecture => invalid_attributes}, valid_session
        expect(assigns(:mini_lecture)).to eq(mini_lecture)
      end

      it "re-renders the 'edit' template" do
        mini_lecture = MiniLecture.create! valid_attributes
        put :update, {:id => mini_lecture.to_param, :mini_lecture => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested mini_lecture" do
      mini_lecture = MiniLecture.create! valid_attributes
      expect {
        delete :destroy, {:id => mini_lecture.to_param}, valid_session
      }.to change(MiniLecture, :count).by(-1)
    end

    it "redirects to the mini_lectures list" do
      mini_lecture = MiniLecture.create! valid_attributes
      delete :destroy, {:id => mini_lecture.to_param}, valid_session
      expect(response).to redirect_to(mini_lectures_url)
    end
  end

end
